version: '2'
services:
  web:
    build: .
    container_name: web
    links:
      - db
    depends_on:
     - db
    ports:
      - 3000:3000
    environment:
      DB_HOST: db
      DB_NAME: sugilanon
      DB_PORT: 3306

  db:
    image: mysql:5.6
    container_name: db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=root
      - MYSQL_DATABASE=sugilanon